version: "3.6"

services:
  postgres:
    image: postgres:11
    container_name: emcs_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    container_name: emcs_web
    image: emcs_web
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    ports:
      - 4200:4200
  api:
    container_name: emcs_api
    image: emcs_api
    build:
      context: .
      dockerfile: EMCS/Dockerfile
    ports:
      - 5000:5000
volumes:
  pgdata:
    name: emcs-pgdata
